name: my_own_mvvm_with_dependency_injection_blackjack_and_hookers
description: "My Own MVVM with Dependency Injection, Blackjack and Hookers"
version: 1.0.2
homepage: https://github.com/JCKodel/my_own_mvvm_with_dependency_injection_blackjack_and_hookers

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  very_good_analysis: ^6.0.0
